### ISSUE TITLE
Cannot Connect to Device

### ISSUE THREAD

**Issue by jkieltyka15** [bboyairwreck/PieMessage#33]
When entering cd PieMessage/PieMessage-Android && gradle installDebug into the terminal, it will get to 97% and fail... throwing the exception it cannot connect to a device. Unsure why this is happening. Both other terminal windows are running in the background and the app was successfully running with the correct ip entered on the android device.

**Comment by Kadwish** [comment]
Sounds like it's trying to side load on to your android device which you don't have loaded onto your MAC. 
I ran the install debug through the Android Studio app and then just exported the .apk onto my phone and ran it from there.
